name: MORL_fast
agent: DQN
env: highway-v0

weights:
  speed: 1.0
  lane: 0.2
  collision: 0.1
  headway: 0.2

train:
  episodes: 200
  gamma: 0.99
  lr: 0.0005
  batch_size: 64
  eps_start: 1.0
  eps_end: 0.05
  eps_decay: 50000
  buffer_size: 100000
  target_update: 1000
